# Generated by Django 4.2.3 on 2023-08-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salute_artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritor',
            name='activo',
            field=models.CharField(max_length=10),
        ),
    ]
