# Generated by Django 4.2.3 on 2023-08-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salute_artist', '0002_alter_escritor_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='activo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pintor',
            name='activo',
            field=models.CharField(max_length=10),
        ),
    ]
