# Generated by Django 4.2.3 on 2023-08-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salute_basic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
